# Generated by Django 3.2.25 on 2024-05-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshfoods', '0002_alter_cart_item_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
