# Generated by Django 3.2.25 on 2024-05-11 17:09

import compressed_image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshfoods', '0002_auto_20240511_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=compressed_image_field.CompressedImageField(default='default.png', height_field=100, null=True, quality=75, upload_to='images', width_field=100),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='img',
            field=compressed_image_field.CompressedImageField(default='default_profile.jpg', height_field=100, null=True, quality=75, upload_to='profiles', width_field=100),
        ),
    ]
