# Generated by Django 3.2.25 on 2024-05-11 17:10

import compressed_image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshfoods', '0003_auto_20240511_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=compressed_image_field.CompressedImageField(default='default.png', height_field='100', null=True, quality=75, upload_to='images', width_field='100'),
        ),
    ]
