# Generated by Django 3.2.25 on 2024-05-11 17:11

import compressed_image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshfoods', '0004_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='img',
            field=compressed_image_field.CompressedImageField(default='default_profile.jpg', height_field='100', null=True, quality=75, upload_to='profiles', width_field='100'),
        ),
    ]
