# Generated by Django 3.2.25 on 2024-05-11 17:16

import compressed_image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshfoods', '0005_alter_profileuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=compressed_image_field.CompressedImageField(default='default.png', null=True, quality=75, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='img',
            field=compressed_image_field.CompressedImageField(default='default_profile.jpg', null=True, quality=1, upload_to='profiles'),
        ),
    ]
