# Generated by Django 3.2.25 on 2024-05-11 17:20

import compressed_image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshfoods', '0007_alter_profileuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='img',
            field=compressed_image_field.CompressedImageField(default='default_profile.jpg', null=True, quality=10, upload_to='profiles'),
        ),
    ]
