# Generated by Django 3.2.25 on 2024-05-11 17:27

import compressed_image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshfoods', '0008_alter_profileuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=compressed_image_field.CompressedImageField(default='default_product.jpg', null=True, quality=50, upload_to='products'),
        ),
    ]
